# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directories:
      - '/.github/actions/setup-environment'
      - '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'uv'
    directory: '/apps/api'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'pre-commit'
    directory: '/apps/api'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    groups:
      commitlint:
        patterns:
          - '@commitlint/*'
      eslint:
        patterns:
          - 'eslint'
          - 'eslint-*'
          - '*-eslint-*'
          - '*/eslint-*'
          - '@eslint/*'
          - 'typescript-eslint'
      eslint:
        patterns:
          - 'prettier'
          - 'prettier-*'
          - '*/eslint-*'
          - '@prettier/*'
          - 'typescript-eslint'
      svelte:
        patterns:
          - 'svelte'
          - 'svelte-*'
          - '@sveltejs/*'
      vite:
        patterns:
          - 'vite'
          - 'vite-*'
          - '@vitejs/*'
          - 'vitest'
          - '@vitest/*'

  - package-ecosystem: 'docker'
    directories:
      - '/apps/api'
      - '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'docker-compose'
    directory: '/'
    schedule:
      interval: 'daily'
