services:
  api:
    extends:
      file: docker-compose.yml
      service: api
    build:
      target: development
    volumes:
      - ./apps/api:/workspace
  web:
    extends:
      file: docker-compose.yml
      service: web
    build:
      target: development
    ports:
      - 24678:24678
    volumes:
      - .:/workspace
      - /workspace/node_modules
      - /workspace/apps/web/node_modules
      - /workspace/packages/client/node_modules
      - /workspace/packages/config/node_modules
      - /workspace/packages/ui/node_modules

