packages:
  - apps/*
  - packages/*

catalog:
  '@sveltejs/adapter-auto': ^7.0.0
  '@sveltejs/kit': ^2.48.0
  '@sveltejs/vite-plugin-svelte': ^6.2.1
  '@tailwindcss/vite': ^4.1.16
  svelte: ^5.42.2
  svelte-check: ^4.3.3
  tailwindcss: ^4.1.16
  tslib: ^2.8.1
  typescript: ^5.9.3
  vite: ^7.1.12

catalogs:
  peers:
    svelte: ^5.0.0
