packages:
  - apps/*
  - packages/*

catalog:
  '@sveltejs/adapter-auto': ^6.1.0
  '@sveltejs/kit': ^2.37.1
  '@sveltejs/vite-plugin-svelte': ^6.1.4
  '@tailwindcss/vite': ^4.1.13
  svelte: ^5.38.7
  svelte-check: ^4.3.1
  tailwindcss: ^4.1.13
  tslib: ^2.8.1
  typescript: ^5.9.2
  vite: ^7.1.4

catalogs:
  peers:
    svelte: ^5.0.0
