packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@sveltejs/adapter-auto': ^6.0.0
  '@sveltejs/kit': ^2.20.8
  '@sveltejs/vite-plugin-svelte': ^5.0.3
  '@tailwindcss/vite': ^4.1.5
  svelte: ^5.28.2
  svelte-check: ^4.1.7
  tailwindcss: ^4.1.5
  tslib: ^2.8.1
  typescript: ^5.8.3
  vite: ^6.3.5

catalogs:
  peers:
    svelte: ^5.0.0
