packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@sveltejs/adapter-auto': ^4.0.0
  '@sveltejs/kit': ^2.17.3
  '@sveltejs/vite-plugin-svelte': ^5.0.3
  '@tailwindcss/vite': ^4.0.9
  svelte: ^5.20.5
  svelte-check: ^4.1.4
  tailwindcss: ^4.0.9
  tslib: ^2.8.1
  typescript: ^5.8.2
  vite: ^6.2.0

catalogs:
  peers:
    svelte: ^5.0.0
