packages:
  - apps/*
  - packages/*

catalog:
  '@sveltejs/adapter-auto': ^7.0.1
  '@sveltejs/kit': ^2.59.1
  '@sveltejs/vite-plugin-svelte': ^7.1.2
  '@tailwindcss/vite': ^4.2.4
  svelte: ^5.55.5
  svelte-check: ^4.4.8
  tailwindcss: ^4.3.0
  tslib: ^2.8.1
  typescript: ^6.0.3
  vite: ^8.0.11

catalogs:
  peers:
    svelte: ^5.0.0
