packages:
  - apps/*
  - packages/*

catalog:
  '@sveltejs/adapter-auto': ^7.0.1
  '@sveltejs/kit': ^2.53.0
  '@sveltejs/vite-plugin-svelte': ^6.2.4
  '@tailwindcss/vite': ^4.2.0
  svelte: ^5.53.2
  svelte-check: ^4.4.3
  tailwindcss: ^4.2.0
  tslib: ^2.8.1
  typescript: ^5.9.3
  vite: ^7.3.1

catalogs:
  peers:
    svelte: ^5.0.0
