packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@sveltejs/adapter-auto': ^4.0.0
  '@sveltejs/kit': ^2.19.2
  '@sveltejs/vite-plugin-svelte': ^5.0.3
  '@tailwindcss/vite': ^4.0.14
  svelte: ^5.23.1
  svelte-check: ^4.1.5
  tailwindcss: ^4.0.14
  tslib: ^2.8.1
  typescript: ^5.8.2
  vite: ^6.2.2

catalogs:
  peers:
    svelte: ^5.0.0
