packages:
  - apps/*
  - packages/*

catalog:
  '@sveltejs/adapter-auto': ^6.1.0
  '@sveltejs/kit': ^2.31.1
  '@sveltejs/vite-plugin-svelte': ^6.1.2
  '@tailwindcss/vite': ^4.1.12
  svelte: ^5.38.1
  svelte-check: ^4.3.1
  tailwindcss: ^4.1.12
  tslib: ^2.8.1
  typescript: ^5.9.2
  vite: ^7.1.2

catalogs:
  peers:
    svelte: ^5.0.0
