packages:
  - apps/*
  - packages/*

catalog:
  '@sveltejs/adapter-auto': ^6.0.1
  '@sveltejs/kit': ^2.22.4
  '@sveltejs/vite-plugin-svelte': ^5.1.0
  '@tailwindcss/vite': ^4.1.11
  svelte: ^5.35.5
  svelte-check: ^4.2.2
  tailwindcss: ^4.1.11
  tslib: ^2.8.1
  typescript: ^5.8.3
  vite: ^7.0.4

catalogs:
  peers:
    svelte: ^5.0.0
