packages:
  - apps/*
  - packages/*

catalog:
  '@sveltejs/adapter-auto': ^6.0.2
  '@sveltejs/kit': ^2.27.3
  '@sveltejs/vite-plugin-svelte': ^6.1.1
  '@tailwindcss/vite': ^4.1.11
  svelte: ^5.38.0
  svelte-check: ^4.3.1
  tailwindcss: ^4.1.11
  tslib: ^2.8.1
  typescript: ^5.9.2
  vite: ^7.1.1

catalogs:
  peers:
    svelte: ^5.0.0
