packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: false

engineStrict: true

catalog:
  '@sveltejs/adapter-auto': ^7.0.1
  '@sveltejs/kit': ^2.67.0
  '@sveltejs/vite-plugin-svelte': ^7.1.2
  '@tailwindcss/vite': ^4.3.1
  svelte: ^5.56.4
  svelte-check: ^4.7.0
  tailwindcss: ^4.3.1
  tslib: ^2.8.1
  typescript: ^6.0.3
  vite: ^8.0.16

catalogs:
  peers:
    svelte: ^5.56.4
