packages:
  - apps/*
  - packages/*

catalog:
  '@sveltejs/adapter-auto': ^7.0.0
  '@sveltejs/kit': ^2.49.2
  '@sveltejs/vite-plugin-svelte': ^6.2.1
  '@tailwindcss/vite': ^4.1.18
  svelte: ^5.46.0
  svelte-check: ^4.3.5
  tailwindcss: ^4.1.18
  tslib: ^2.8.1
  typescript: ^5.9.3
  vite: ^7.3.0

catalogs:
  peers:
    svelte: ^5.0.0
