packages:
  - apps/*
  - packages/*

catalog:
  '@sveltejs/adapter-auto': ^7.0.0
  '@sveltejs/kit': ^2.49.1
  '@sveltejs/vite-plugin-svelte': ^6.2.1
  '@tailwindcss/vite': ^4.1.17
  svelte: ^5.45.6
  svelte-check: ^4.3.4
  tailwindcss: ^4.1.17
  tslib: ^2.8.1
  typescript: ^5.9.3
  vite: ^7.2.7

catalogs:
  peers:
    svelte: ^5.0.0
