packages:
  - apps/*
  - packages/*

catalog:
  '@sveltejs/adapter-auto': ^6.0.1
  '@sveltejs/kit': ^2.26.1
  '@sveltejs/vite-plugin-svelte': ^6.1.0
  '@tailwindcss/vite': ^4.1.11
  svelte: ^5.37.1
  svelte-check: ^4.3.0
  tailwindcss: ^4.1.11
  tslib: ^2.8.1
  typescript: ^5.8.3
  vite: ^7.0.6

catalogs:
  peers:
    svelte: ^5.0.0
