packages:
  - apps/*
  - packages/*

catalog:
  '@sveltejs/adapter-auto': ^7.0.1
  '@sveltejs/kit': ^2.55.0
  '@sveltejs/vite-plugin-svelte': ^7.0.0
  '@tailwindcss/vite': ^4.2.2
  svelte: ^5.54.0
  svelte-check: ^4.4.5
  tailwindcss: ^4.2.2
  tslib: ^2.8.1
  typescript: ^5.9.3
  vite: ^8.0.1

catalogs:
  peers:
    svelte: ^5.0.0
