packages:
  - apps/*
  - packages/*

catalog:
  '@sveltejs/adapter-auto': ^7.0.0
  '@sveltejs/kit': ^2.48.4
  '@sveltejs/vite-plugin-svelte': ^6.2.1
  '@tailwindcss/vite': ^4.1.17
  svelte: ^5.43.5
  svelte-check: ^4.3.3
  tailwindcss: ^4.1.17
  tslib: ^2.8.1
  typescript: ^5.9.3
  vite: ^7.2.2

catalogs:
  peers:
    svelte: ^5.0.0
