name: Setup environment
description: Setup CI environment
inputs:
  node-version:
    description: Node version to use
    required: false
    default: '22'
  pnpm-version:
    description: PNPM version to use
    required: false
  python-version:
    description: Python version to use
    required: false
    default: '3.13'
  poetry-version:
    description: Poetry version to use
    required: false
    default: 2.1.1

runs:
  using: 'composite'
  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Setup Poetry
      uses: abatilo/actions-poetry@v4
      with:
        poetry-version: ${{ inputs.poetry-version }}
