name: Setup environment
description: Setup CI environment
inputs:
  node-version:
    description: Node version to use
    required: false
    default: '24'
  python-version:
    description: Python version to use
    required: false
    default: '3.14'

runs:
  using: 'composite'
  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@v4
    - name: Setup Node
      uses: actions/setup-node@v5
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
    - name: Setup Poetry
      run: pipx install "poetry>=2.0,<3.0"
      shell: bash
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'poetry'
