import json
import logging
import os
import pathlib
from collections.abc import AsyncGenerator
from contextlib import asynccontextmanager
from logging.handlers import RotatingFileHandler
from typing import Any

from fastapi import FastAPI
from fastapi import routing
from fastapi.middleware.cors import CORSMiddleware

from .routers import batch
from .routers import downloads
from .routers import search
from .routers import session
from .routers import versions
from .session import session_manager

handler = RotatingFileHandler(
    "output.log",
    maxBytes=1024 * 1024 * 5,  # 5 MB
    backupCount=5,
)
logging.basicConfig(
    format="[%(asctime)s] %(levelname)s - %(name)s - %(module)s - %(funcName)s: %(message)s",  # noqa: E501
    datefmt="%Y-%m-%d %H:%M:%S",
    level=logging.WARNING,
    handlers=[handler],
)


# Read the package.json file for the API. Relevant details from in it will be
# used in the swagger and redoc documentation auto-generated by FastAPI.
project_data: dict[str, Any] = {}
project_data_path = pathlib.Path(__file__).parent.parent / "package.json"
with project_data_path.open("rb") as f:
    project_data = json.load(f)


# This function requires that the names for each route be unique. Without
# this being the case, the OpenAPI specification generated by FastAPI will
# have duplicate entries.
# We specifically override this function and put the burden on the developer
# to ensure that the generated API client has better function names.
def generate_custom_unique_id(route: routing.APIRoute) -> str:
    return route.name


@asynccontextmanager
async def lifespan(_: FastAPI) -> AsyncGenerator:
    yield
    session_manager.cleanup(force=True)


app = FastAPI(
    title=project_data["name"],
    summary=project_data["description"],
    contact={
        "name": "GitHub",
        "url": project_data["repository"]["url"],
    },
    license_info={
        "name": project_data["license"],
        "url": f"{project_data['repository']['url']}/blob/main/LICENSE",
    },
    openapi_tags=[
        {"name": "session", "description": "User session handling."},
        {"name": "search", "description": "YouTube search handling."},
        {
            "name": "downloads",
            "description": "Single video downloading handling and management.",
        },
        {"name": "batch", "description": "Batch download handling and management."},
        {"name": "versions", "description": "Version details for the application."},
    ],
    version=project_data["version"],
    generate_unique_id_function=generate_custom_unique_id,
    lifespan=lifespan,
)

# Allow any localhost address origins to access the API.
allow_origins = [
    "http://localhost",
    "http://localhost:5173",
    "http://127.0.0.1",
    "http://127.0.0.1:5173",
]

# Allow an additional origin specfied via environment variable if it exists.
additional_origin = os.environ.get("ALLOWED_ORIGIN", None)
if additional_origin is not None:
    allow_origins.append(additional_origin)

app.add_middleware(
    CORSMiddleware,
    allow_origins=allow_origins,
    allow_credentials=True,
    allow_methods=["POST", "PUT", "GET", "DELETE"],
    allow_headers=["*"],
)

app.include_router(session.router)
app.include_router(search.router)
app.include_router(downloads.router)
app.include_router(batch.router)
app.include_router(versions.router)
