files: ^(apps/api/)
repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.7
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.11
    hooks:
      - id: ruff-check
      - id: ruff-format
  - repo: local
    hooks:
      - id: local-mypy
        name: mypy check
        entry: uv run mypy --ignore-missing-imports .
        require_serial: true
        language: unsupported
        pass_filenames: false
      - id: local-ty
        name: ty check
        entry: uv run ty check .
        require_serial: true
        language: unsupported
        pass_filenames: false
