name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  ci:
    name: CI (Lint, Check, Build)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: ['22', '24', '26']
        python-version: ['3.13', '3.14']
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-environment
        with:
          node-version: ${{ matrix.node-version }}
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm lint
      - name: Check
        run: pnpm check
      - name: Build
        run: pnpm build
