name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          node-version: '24'
          python-version: '3.14'
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          title: 'Changesets Release'
          commit: 'chore: release'
          version: pnpm changeset version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
